In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.chdir('D:\\python\\data')

In [3]:
ds=pd.read_csv('Python_Module_Day_15.2_Credit_Risk_Train_data_XTRAIN.csv')

In [4]:
ds

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No         3+      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes         3+      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [5]:
ds_train=ds.drop('Loan_ID', 1)

In [6]:
ds_train

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
5      Male     Yes          2      Graduate           Yes             5417   
6      Male     Yes          0  Not Graduate            No             2333   
7      Male     Yes         3+      Graduate            No             3036   
8      Male     Yes          2      Graduate            No             4006   
9      Male     Yes          1      Graduate            No            12841   
10     Male     Yes          2      Graduate            No             3200   
11     Male     Yes          2      Graduate           NaN             2500   
12     Male     Yes          2      Graduate            No             3073   
13     Male      No          0      Graduate            No             1853   
14     Male     Yes          2      Graduate            No             1299   
15     Male      No          0      Graduate            No             4950   
16     Male      No          1  Not Graduate            No             3596   
17   Female      No          0      Graduate            No             3510   
18     Male     Yes          0  Not Graduate            No             4887   
19     Male     Yes          0      Graduate           NaN             2600   
20     Male     Yes          0  Not Graduate            No             7660   
21     Male     Yes          1      Graduate            No             5955   
22     Male     Yes          0  Not Graduate            No             2600   
23      NaN     Yes          2  Not Graduate            No             3365   
24     Male     Yes          1      Graduate           NaN             3717   
25     Male     Yes          0      Graduate           Yes             9560   
26     Male     Yes          0      Graduate            No             2799   
27     Male     Yes          2  Not Graduate            No             4226   
28     Male      No          0  Not Graduate            No             1442   
29   Female      No          2      Graduate           NaN             3750   
..      ...     ...        ...           ...           ...              ...   
584    Male     Yes          1      Graduate            No             2787   
585    Male     Yes          1      Graduate            No             4283   
586    Male     Yes          0      Graduate            No             2297   
587  Female      No          0  Not Graduate            No             2165   
588     NaN      No          0      Graduate            No             4750   
589    Male     Yes          2      Graduate           Yes             2726   
590    Male     Yes          0      Graduate            No             3000   
591    Male     Yes          2      Graduate           Yes             6000   
592     NaN      No         3+      Graduate           Yes             9357   
593    Male     Yes          0      Graduate            No             3859   
594    Male     Yes          0      Graduate           Yes            16120   
595    Male      No          0  Not Graduate            No             3833   
596    Male     Yes          2  Not Graduate           Yes             6383   
597    Male      No        NaN      Graduate            No             2987   
598    Male     Yes          0      Graduate           Yes             9963   
599    Male     Yes          2      Graduate            No             5780   
600  Female      No         3+      Graduate           NaN              416   
601    Male     Yes          0  Not Graduate           NaN             2894   
602    Male     Yes         3+      Graduate           

In [7]:
ds_train.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
import seaborn as sns

In [9]:
Q1 = ds_train.quantile(0.25)
Q3 = ds_train.quantile(0.75)
IQR = Q3-Q1

In [10]:
ds_train= ds_train[~((ds_train<(Q1-1.5*IQR))
                       | (ds_train>(Q3+1.5*IQR))).any(axis=1)]

In [11]:
ds_train

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
5      Male     Yes          2      Graduate           Yes             5417   
6      Male     Yes          0  Not Graduate            No             2333   
8      Male     Yes          2      Graduate            No             4006   
10     Male     Yes          2      Graduate            No             3200   
11     Male     Yes          2      Graduate           NaN             2500   
13     Male      No          0      Graduate            No             1853   
15     Male      No          0      Graduate            No             4950   
18     Male     Yes          0  Not Graduate            No             4887   
19     Male     Yes          0      Graduate           NaN             2600   
24     Male     Yes          1      Graduate           NaN             3717   
25     Male     Yes          0      Graduate           Yes             9560   
26     Male     Yes          0      Graduate            No             2799   
27     Male     Yes          2  Not Graduate            No             4226   
28     Male      No          0  Not Graduate            No             1442   
29   Female      No          2      Graduate           NaN             3750   
30     Male     Yes          1      Graduate           NaN             4166   
31     Male      No          0      Graduate            No             3167   
32     Male      No          1      Graduate           Yes             4692   
33     Male     Yes          0      Graduate            No             3500   
35     Male     Yes          0      Graduate            No             2275   
37   Female     Yes          0      Graduate            No             3667   
39     Male      No          0  Not Graduate            No             3748   
40     Male      No          0      Graduate            No             3600   
41     Male      No          0      Graduate            No             1800   
42     Male     Yes          0      Graduate            No             2400   
..      ...     ...        ...           ...           ...              ...   
560    Male     Yes          2  Not Graduate            No             3675   
562    Male     Yes          0      Graduate            No             5923   
563    Male      No          0  Not Graduate           Yes             5800   
565    Male     Yes          0  Not Graduate            No             4467   
566    Male      No          0      Graduate            No             3333   
568  Female      No          0      Graduate            No             2378   
570    Male     Yes          1      Graduate            No             3417   
574    Male     Yes         3+      Graduate            No             6406   
577    Male      No          0      Graduate            No             3229   
578    Male     Yes          1      Graduate            No             1782   
579    Male      No          0      Graduate           NaN             3182   
580    Male     Yes          2      Graduate            No             6540   
582  Female     Yes          0      Graduate            No             3166   
583    Male     Yes          1      Graduate            No             1880   
586    Male     Yes          0      Graduate            No             2297   
587  Female      No          0  Not Graduate            No             2165   
588     NaN      No          0      Graduate            No             4750   
595    Male      No          0  Not Graduate            No             3833   
596    Male     Yes          2  Not Graduate           

In [12]:
ds_train.groupby('Self_Employed').size()

Self_Employed
No     325
Yes     47
dtype: int64

In [13]:
#gender
ds_train.groupby('Gender').agg({'Gender': np.size})
ds_train["Gender"]=ds_train["Gender"].fillna('Male')
ds_train["Gender"] = ds_train["Gender"].astype('category')
ds_train["Gender"] = ds_train["Gender"].cat.codes
#married
ds_train.groupby('Married').agg({'Married': np.size})
ds_train["Married"]=ds_train["Married"].fillna('Yes')
ds_train["Married"] = ds_train["Married"].astype('category')
ds_train["Married"] = ds_train["Married"].cat.codes
#Dependents 
ds_train.groupby('Dependents').agg({'Dependents': np.size})
ds_train["Dependents"]=ds_train["Dependents"].fillna(0)
ds_train["Dependents"] = ds_train["Dependents"].astype('category')
ds_train["Dependents"] = ds_train["Dependents"].cat.codes
#Self_Employed 
ds_train.groupby('Self_Employed').agg({'Self_Employed': np.size})
ds_train["Self_Employed"]=ds_train["Self_Employed"].fillna('No')
ds_train["Self_Employed"] = ds_train["Self_Employed"].astype('category')
ds_train["Self_Employed"] = ds_train["Self_Employed"].cat.codes


C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value i

In [14]:
#LoanAmount
ds_train["LoanAmount"].fillna(ds_train["LoanAmount"].mean(), inplace=True)
#Loan_Amount_Term
ds_train["Loan_Amount_Term"].fillna(ds_train["Loan_Amount_Term"].mean(), inplace=True)
#Credit_History
ds_train["Credit_History"].fillna(ds_train["Credit_History"].mean(), inplace=True)

C:\Users\Hp\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [15]:
#Gender
ds_train= pd.get_dummies(ds_train,columns=['Gender'],drop_first=True)
#Married
#ds_train= pd.get_dummies(ds_train,columns=['Married'],drop_first=True)
#Dependents
#ds_train= pd.get_dummies(ds_train,columns=['Dependents'],drop_first=True)
#Self_Employed
#ds_train= pd.get_dummies(ds_train,columns=['Self_Employed'],drop_first=True)
#Loan_Status
#ds_train= pd.get_dummies(ds_train,columns=['Loan_Status'],drop_first=True)
#Eduction
#ds_train= pd.get_dummies(ds_train,columns=['Education'],drop_first=True)
#Property area
#ds_train= pd.get_dummies(ds_train,columns=['Property_Area'],drop_first=True)


In [16]:
ds_train= pd.get_dummies(ds_train,columns=['Married'],drop_first=True)

In [17]:
ds_train= pd.get_dummies(ds_train,columns=['Dependents'],drop_first=True)

In [18]:
ds_train= pd.get_dummies(ds_train,columns=['Self_Employed'],drop_first=True)

In [19]:
ds_train= pd.get_dummies(ds_train,columns=['Loan_Status'],drop_first=True)

In [20]:
ds_train= pd.get_dummies(ds_train,columns=['Education'],drop_first=True)

In [21]:
ds_train= pd.get_dummies(ds_train,columns=['Property_Area'],drop_first=True)

In [22]:
ds_train

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  129.205195             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
5               5417             4196.0  267.000000             360.0   
6               2333             1516.0   95.000000             360.0   
8               4006             1526.0  168.000000             360.0   
10              3200              700.0   70.000000             360.0   
11              2500             1840.0  109.000000             360.0   
13              1853             2840.0  114.000000             360.0   
15              4950                0.0  125.000000             360.0   
18              4887                0.0  133.000000             360.0   
19              2600             3500.0  115.000000             360.0   
24              3717             2925.0  151.000000             360.0   
25              9560                0.0  191.000000             360.0   
26              2799             2253.0  122.000000             360.0   
27              4226             1040.0  110.000000             360.0   
28              1442                0.0   35.000000             360.0   
29              3750             2083.0  120.000000             360.0   
30              4166             3369.0  201.000000             360.0   
31              3167                0.0   74.000000             360.0   
32              4692                0.0  106.000000             360.0   
33              3500             1667.0  114.000000             360.0   
35              2275             2067.0  129.205195             360.0   
37              3667             1459.0  144.000000             360.0   
39              3748             1668.0  110.000000             360.0   
40              3600                0.0   80.000000             360.0   
41              1800             1213.0   47.000000             360.0   
42              2400                0.0   75.000000             360.0   
..               ...                ...         ...               ...   
560             3675              242.0  108.000000             360.0   
562             5923             2054.0  211.000000             360.0   
563             5800                0.0  132.000000             360.0   
565             4467                0.0  120.000000             360.0   
566             3333                0.0   70.000000             360.0   
568             2378                0.0    9.000000             360.0   
570             3417             1750.0  186.000000             360.0   
574             6406                0.0  150.000000             360.0   
577             3229             2739.0  110.000000             360.0   
578             1782             2232.0  107.000000             360.0   
579             3182             2917.0  161.000000             360.0   
580             6540                0.0  205.000000             360.0   
582             3166                0.0   36.000000             360.0   
583             1880                0.0   61.000000             360.0   
586             2297             1522.0  104.000000             360.0   
587             2165                0.0   70.000000             360.0   
588             4750                0.0   94.000000             360.0   
595             3833                0.0  110.000000             360.0   
596             6383             1000.0  187.000000             360.0   
598             9963                0.0  180.000000             360.0   
599             5780                0.0  192.000000             360.0   
601             2894             2792.0  155.000000             360.0   
602             5703                0.0  128.000000            

In [23]:
os.chdir("D:\\python\\data")

In [24]:
ds2=pd.read_csv("Python_Module_Day_15.4_Credit_Risk_Validate_data_XTEST.csv")

In [25]:
ds2

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001015    Male     Yes          0      Graduate            No   
1    LP001022    Male     Yes          1      Graduate            No   
2    LP001031    Male     Yes          2      Graduate            No   
3    LP001035    Male     Yes          2      Graduate            No   
4    LP001051    Male      No          0  Not Graduate            No   
5    LP001054    Male     Yes          0  Not Graduate           Yes   
6    LP001055  Female      No          1  Not Graduate            No   
7    LP001056    Male     Yes          2  Not Graduate            No   
8    LP001059    Male     Yes          2      Graduate           NaN   
9    LP001067    Male      No          0  Not Graduate            No   
10   LP001078    Male      No          0  Not Graduate            No   
11   LP001082    Male     Yes          1      Graduate           NaN   
12   LP001083    Male      No         3+      Graduate            No   
13   LP001094    Male     Yes          2      Graduate           NaN   
14   LP001096  Female      No          0      Graduate            No   
15   LP001099    Male      No          1      Graduate            No   
16   LP001105    Male     Yes          2      Graduate            No   
17   LP001107    Male     Yes         3+      Graduate            No   
18   LP001108    Male     Yes          0      Graduate            No   
19   LP001115    Male      No          0      Graduate            No   
20   LP001121    Male     Yes          1  Not Graduate            No   
21   LP001124  Female      No         3+  Not Graduate            No   
22   LP001128     NaN      No          0      Graduate            No   
23   LP001135  Female      No          0  Not Graduate            No   
24   LP001149    Male     Yes          0      Graduate            No   
25   LP001153    Male      No          0      Graduate            No   
26   LP001163    Male     Yes          2      Graduate            No   
27   LP001169    Male     Yes          0      Graduate            No   
28   LP001174    Male     Yes          0      Graduate            No   
29   LP001176    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
337  LP002856    Male     Yes          0      Graduate            No   
338  LP002857    Male     Yes          1      Graduate           Yes   
339  LP002858  Female      No          0      Graduate            No   
340  LP002860    Male     Yes          0      Graduate           Yes   
341  LP002867    Male      No          0      Graduate           Yes   
342  LP002869    Male     Yes         3+  Not Graduate            No   
343  LP002870    Male     Yes          1      Graduate            No   
344  LP002876    Male      No          0      Graduate            No   
345  LP002878    Male     Yes         3+      Graduate            No   
346  LP002879    Male     Yes          0      Graduate            No   
347  LP002885    Male      No          0  Not Graduate            No   
348  LP002890    Male     Yes          2  Not Graduate            No   
349  LP002891    Male     Yes          0      Graduate           Yes   
350  LP002899    Male     Yes          2      Graduate            No   
351  LP002901    Male      No          0      Graduate            No   
352  LP002907    Male     Yes          0      Graduate            No   
353  LP002920    Male     Yes          0      Graduate            No   
354  LP002921    Male     Yes         3+  Not Graduate            No   
355  LP002932    Male     Yes         3+      Graduate            No   
356  LP002935    Male     Yes          1      Graduate            No   
357  LP002952    Male      No          0      Graduate            No   
358  LP002954    Male     Yes          2  Not Graduate            No   
359  LP002962    Male      No          0      Graduate            No   
360  LP002965  Female     Yes          0      

In [26]:
dsp=ds2.drop('Loan_ID', 1)

In [27]:
Q1 = dsp.quantile(0.25)
Q3 = dsp.quantile(0.75)
IQR = Q3-Q1

In [28]:
ds_test= dsp[~((dsp<(Q1-1.5*IQR))
                       | (dsp>(Q3+1.5*IQR))).any(axis=1)]

In [29]:
ds_test

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male     Yes          0      Graduate            No             5720   
1      Male     Yes          1      Graduate            No             3076   
2      Male     Yes          2      Graduate            No             5000   
3      Male     Yes          2      Graduate            No             2340   
4      Male      No          0  Not Graduate            No             3276   
5      Male     Yes          0  Not Graduate           Yes             2165   
6    Female      No          1  Not Graduate            No             2226   
9      Male      No          0  Not Graduate            No             2400   
10     Male      No          0  Not Graduate            No             3091   
11     Male     Yes          1      Graduate           NaN             2185   
14   Female      No          0      Graduate            No             4666   
15     Male      No          1      Graduate            No             5667   
16     Male     Yes          2      Graduate            No             4583   
17     Male     Yes         3+      Graduate            No             3786   
20     Male     Yes          1  Not Graduate            No             1888   
22      NaN      No          0      Graduate            No             3909   
23   Female      No          0  Not Graduate            No             3765   
26     Male     Yes          2      Graduate            No             4363   
28     Male     Yes          0      Graduate            No             3772   
30   Female      No          0  Not Graduate            No             2478   
31     Male     Yes          2      Graduate            No             6250   
32     Male      No          0      Graduate            No             3268   
33     Male     Yes          0      Graduate            No             2783   
34     Male     Yes          0      Graduate            No             2740   
37     Male     Yes          0      Graduate           Yes             2267   
38     Male      No          0      Graduate           Yes             5833   
39     Male      No          0      Graduate            No             3643   
40     Male     Yes          0      Graduate            No             5629   
41   Female      No          0      Graduate            No             3644   
42     Male     Yes          0  Not Graduate            No             1750   
..      ...     ...        ...           ...           ...              ...   
321  Female     Yes          0  Not Graduate            No             1647   
324    Male     Yes          0      Graduate            No             5333   
326    Male     Yes          1  Not Graduate           NaN             2600   
327    Male     Yes          2      Graduate            No             5041   
328    Male     Yes         3+      Graduate           Yes             6958   
329    Male     Yes          1      Graduate            No             3500   
330    Male     Yes          0      Graduate            No             5509   
332  Female     Yes          1  Not Graduate            No             3621   
333  Female     Yes          0      Graduate            No             4709   
334    Male     Yes          0      Graduate            No             1516   
335    Male      No          2      Graduate            No             2400   
336  Female      No          0  Not Graduate            No             3015   
337    Male     Yes          0      Graduate            No             2292   
341    Male      No          0      Graduate           Yes             3972   
343    Male     Yes          1      Graduate            No             4700   
344    Male      No          0      Graduate            No             6858   
347    Male      No          0  Not Graduate            No             2868   
348    Male     Yes          2  Not Graduate            No             3418   
352    Male     Yes          0      Graduate           

In [30]:
ds_test.isnull().sum()

Gender                8
Married               0
Dependents            6
Education             0
Self_Employed         9
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            2
Loan_Amount_Term      4
Credit_History       23
Property_Area         0
outcome               0
dtype: int64

In [31]:
ds_test.groupby('Self_Employed').size()

Self_Employed
No     201
Yes     26
dtype: int64

In [32]:
#gender
ds_test.groupby('Gender').agg({'Gender': np.size})
ds_test["Gender"]=ds_test["Gender"].fillna('Male')
ds_test["Gender"] = ds_test["Gender"].astype('category')
ds_test["Gender"] = ds_test["Gender"].cat.codes
#depen
ds_test.groupby('Dependents').agg({'Dependents': np.size})
ds_test["Dependents"]=ds_test["Dependents"].fillna(0)
ds_test["Dependents"] = ds_test["Dependents"].astype('category')
ds_test["Dependents"] = ds_test["Dependents"].cat.codes
#self employ
ds_test.groupby('Self_Employed').agg({'Self_Employed': np.size})
ds_test["Self_Employed"]=ds_test["Self_Employed"].fillna('No')
ds_test["Self_Employed"] = ds_test["Self_Employed"].astype('category')
ds_test["Self_Employed"] = ds_test["Self_Employed"].cat.codes


C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value i

In [33]:
#LoanAmount
ds_test["LoanAmount"].fillna(ds_test["LoanAmount"].mean(), inplace=True)
#Loan_Amount_Term
ds_test["Loan_Amount_Term"].fillna(ds_test["Loan_Amount_Term"].mean(), inplace=True)
#Credit_History
ds_test["Credit_History"].fillna(ds_test["Credit_History"].mean(), inplace=True)

In [34]:
ds_test= pd.get_dummies(ds_test,columns=['Married'],drop_first=True)

In [35]:
ds_test= pd.get_dummies(ds_test,columns=['Education'],drop_first=True)

In [36]:
ds_test= pd.get_dummies(ds_test,columns=['Property_Area'],drop_first=True)

In [37]:
ds_test= pd.get_dummies(ds_test,columns=['outcome'],drop_first=True)

In [54]:
ds_test= pd.get_dummies(ds_test,columns=['Dependents'],drop_first=True)

In [55]:
x_train=ds_train.iloc[:,:-1]

In [56]:
x_train

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  129.205195             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
5               5417             4196.0  267.000000             360.0   
6               2333             1516.0   95.000000             360.0   
8               4006             1526.0  168.000000             360.0   
10              3200              700.0   70.000000             360.0   
11              2500             1840.0  109.000000             360.0   
13              1853             2840.0  114.000000             360.0   
15              4950                0.0  125.000000             360.0   
18              4887                0.0  133.000000             360.0   
19              2600             3500.0  115.000000             360.0   
24              3717             2925.0  151.000000             360.0   
25              9560                0.0  191.000000             360.0   
26              2799             2253.0  122.000000             360.0   
27              4226             1040.0  110.000000             360.0   
28              1442                0.0   35.000000             360.0   
29              3750             2083.0  120.000000             360.0   
30              4166             3369.0  201.000000             360.0   
31              3167                0.0   74.000000             360.0   
32              4692                0.0  106.000000             360.0   
33              3500             1667.0  114.000000             360.0   
35              2275             2067.0  129.205195             360.0   
37              3667             1459.0  144.000000             360.0   
39              3748             1668.0  110.000000             360.0   
40              3600                0.0   80.000000             360.0   
41              1800             1213.0   47.000000             360.0   
42              2400                0.0   75.000000             360.0   
..               ...                ...         ...               ...   
560             3675              242.0  108.000000             360.0   
562             5923             2054.0  211.000000             360.0   
563             5800                0.0  132.000000             360.0   
565             4467                0.0  120.000000             360.0   
566             3333                0.0   70.000000             360.0   
568             2378                0.0    9.000000             360.0   
570             3417             1750.0  186.000000             360.0   
574             6406                0.0  150.000000             360.0   
577             3229             2739.0  110.000000             360.0   
578             1782             2232.0  107.000000             360.0   
579             3182             2917.0  161.000000             360.0   
580             6540                0.0  205.000000             360.0   
582             3166                0.0   36.000000             360.0   
583             1880                0.0   61.000000             360.0   
586             2297             1522.0  104.000000             360.0   
587             2165                0.0   70.000000             360.0   
588             4750                0.0   94.000000             360.0   
595             3833                0.0  110.000000             360.0   
596             6383             1000.0  187.000000             360.0   
598             9963                0.0  180.000000             360.0   
599             5780                0.0  192.000000             360.0   
601             2894             2792.0  155.000000             360.0   
602             5703                0.0  128.000000            

In [60]:
y_train=ds_train.iloc[:,-1]

In [61]:
y_train.values

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [62]:
x_test=ds_test

In [63]:
x_test=ds_test.iloc[:,:-1]

In [64]:
x_test

Gender  Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0         1              0             5720                  0       110.0   
1         1              0             3076               1500       126.0   
2         1              0             5000               1800       208.0   
3         1              0             2340               2546       100.0   
4         1              0             3276                  0        78.0   
5         1              1             2165               3422       152.0   
6         0              0             2226                  0        59.0   
9         1              0             2400               2400       123.0   
10        1              0             3091                  0        90.0   
11        1              0             2185               1516       162.0   
14        0              0             4666                  0       124.0   
15        1              0             5667                  0       131.0   
16        1              0             4583               2916       200.0   
17        1              0             3786                333       126.0   
20        1              0             1888               1620        48.0   
22        1              0             3909                  0       101.0   
23        0              0             3765                  0       125.0   
26        1              0             4363               1250       140.0   
28        1              0             3772                833        57.0   
30        0              0             2478                  0        75.0   
31        1              0             6250                820       192.0   
32        1              0             3268               1683       152.0   
33        1              0             2783               2708       158.0   
34        1              0             2740               1541       101.0   
37        1              1             2267               2792        90.0   
38        1              1             5833                  0       116.0   
39        1              0             3643               1963       138.0   
40        1              0             5629                818       100.0   
41        0              0             3644                  0       110.0   
42        1              0             1750               2024        90.0   
..      ...            ...              ...                ...         ...   
321       0              0             1647               1762       181.0   
324       1              0             5333                  0        90.0   
326       1              0             2600                618       122.0   
327       1              0             5041                700       150.0   
328       1              1             6958               1411       150.0   
329       1              0             3500               1658       104.0   
330       1              0             5509                  0       143.0   
332       0              0             3621               2717       171.0   
333       0              0             4709                  0       113.0   
334       1              0             1516               1951        35.0   
335       1              0             2400                  0        46.0   
336       0              0             3015               2000       145.0   
337       1              0             2292               1558       119.0   
341       1              1             3972               4275       187.0   
343       1              0             4700                  0        80.0   
344       1              0             6858                  0       176.0   
347       1              0             2868                  0        70.0   
348       1              0             3418               1380       135.0   
352       1              0             5817                910       109.0   
353       1              0 

In [65]:
y_test=ds_test.iloc[:,-1]

In [66]:
y_test.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [67]:
from sklearn.preprocessing import StandardScaler
sc_x_test = StandardScaler()
x_test = sc_x_test.fit_transform(x_test)

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [68]:
x_test

array([[ 0.49204193, -0.35186578,  1.18442608, ...,  0.85749293,
        -0.45853725, -0.41728809],
       [ 0.49204193, -0.35186578, -0.58547081, ..., -1.16619038,
         2.1808479 , -0.41728809],
       [ 0.49204193, -0.35186578,  0.70245718, ..., -1.16619038,
        -0.45853725,  2.39642591],
       ...,
       [ 0.49204193, -0.35186578,  0.13882134, ...,  0.85749293,
        -0.45853725, -0.41728809],
       [ 0.49204193, -0.35186578, -0.46899499, ...,  0.85749293,
        -0.45853725, -0.41728809],
       [ 0.49204193, -0.35186578,  0.70245718, ...,  0.85749293,
        -0.45853725, -0.41728809]])

In [69]:
from sklearn.preprocessing import StandardScaler
sc_x_train = StandardScaler()
x_train = sc_x_train.fit_transform(x_train)

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [70]:
x_train

array([[ 0.95605666, -0.95729352,  0.        , ...,  0.48186942,
        -0.52501526, -0.80288735],
       [ 0.27659653,  0.10255261, -0.02624463, ..., -2.07525099,
        -0.52501526, -0.80288735],
       [-0.57299697, -0.95729352, -1.37637258, ...,  0.48186942,
        -0.52501526, -0.80288735],
       ...,
       [-0.6266668 , -0.95729352, -1.26749129, ...,  0.48186942,
        -0.52501526, -0.80288735],
       [ 2.14913711, -0.78861774,  2.69578752, ...,  0.48186942,
        -0.52501526, -0.80288735],
       [ 1.88669161, -0.95729352,  1.25855454, ...,  0.48186942,
        -0.52501526, -0.80288735]])

In [71]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='sigmoid')
classifier_svm.fit(x_train,y_train)

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [72]:
y_pred = classifier_svm.predict(x_test)

In [73]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0], dtype=uint8)

In [74]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.72

array([[165,  53],
       [ 13,   5]], dtype=int64)

In [75]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='linear')
classifier_svm.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [76]:
y_pred = classifier_svm.predict(x_test)

In [77]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1], dtype=uint8)

In [78]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.66

array([[150,  68],
       [ 12,   6]], dtype=int64)

In [79]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='rbf')
classifier_svm.fit(x_train,y_train)

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [80]:
y_pred = classifier_svm.predict(x_test)

In [81]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=uint8)

In [82]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.66

array([[149,  69],
       [ 11,   7]], dtype=int64)

In [92]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='poly')
classifier_svm.fit(x_train,y_train)

C:\Users\Hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='poly', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [93]:
y_pred = classifier_svm.predict(x_test)

In [94]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.88

array([[210,   8],
       [ 18,   0]], dtype=int64)

In [85]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [86]:
y_pred = classifier_dt.predict(x_test)

In [87]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1], dtype=uint8)

In [88]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.55

array([[120,  98],
       [  6,  12]], dtype=int64)

In [89]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [90]:
y_pred = classifier_rf.predict(x_test)

In [91]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
#0.60

array([[136,  82],
       [ 12,   6]], dtype=int64)